[package]
name = "hub-data"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
l2-core = { path = "../l2-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
