[ippan]
rpc_url = "env:IPPAN_RPC_URL"
poll_interval_ms = 10000
subject_type = "validator"

[ethereum]
rpc_url = "env:ETH_RPC_URL"
chain_id = 11155111
oracle_contract_address = "0x0000000000000000000000000000000000000000"

[security]
score_scale = 1000000
max_updates_per_round = 100
